[$trunkdevice]
type=friend
nat=yes
context=from-trunk-sip
accountcode=$trunkdevice
username=$username
secret=$secret
host=$host
port=$port
register=$register
fromuser=$fromuser
fromdomain=$fromdomain
callerid=$callerid
defaultexpiry=$defaultexpiry
call-limit=$call-limit
insecure=$insecure
progressinband=$progressinband
qualify=$qualify
disallow=all
allow=$allow
;customize follow
